# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-12 06:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '系统设置',
            },
        ),
        migrations.CreateModel(
            name='CommonUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=32, unique=True)),
                ('username', models.CharField(max_length=1024, verbose_name='用户名')),
                ('password', models.CharField(max_length=1024, verbose_name='密码')),
                ('gender', models.IntegerField(choices=[(0, '男'), (1, '女')], default=0)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatar', verbose_name='头像')),
                ('qq', models.CharField(blank=True, max_length=32, null=True)),
                ('wechat', models.CharField(blank=True, max_length=32, null=True)),
                ('money', models.FloatField(default=0.0, verbose_name='余额')),
                ('in_order_money', models.FloatField(default=0.1, verbose_name='冻结金额')),
            ],
            options={
                'verbose_name': '普通用户',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(verbose_name='订单类型')),
                ('price', models.FloatField(verbose_name='价格')),
                ('place', models.CharField(max_length=1024, verbose_name='地点')),
                ('place_type', models.IntegerField(choices=[(0, '室内'), (1, '户外')], default=0)),
                ('year', models.IntegerField(default=2018, verbose_name='年')),
                ('month', models.IntegerField(default=1, verbose_name='月')),
                ('day', models.IntegerField(default=1, verbose_name='日')),
                ('model_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wephoto.CommonUser', verbose_name='用户')),
            ],
            options={
                'verbose_name': '订单',
            },
        ),
        migrations.CreateModel(
            name='OrderComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=5, verbose_name='分数')),
                ('content', models.CharField(max_length=4096)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wephoto.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Photographer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=32, unique=True)),
                ('username', models.CharField(max_length=1024, verbose_name='用户名')),
                ('password', models.CharField(max_length=1024, verbose_name='密码')),
                ('gender', models.IntegerField(choices=[(0, '男'), (1, '女')], default=0)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatar', verbose_name='头像')),
                ('qq', models.CharField(blank=True, max_length=32, null=True)),
                ('wechat', models.CharField(blank=True, max_length=32, null=True)),
                ('money', models.FloatField(default=0.0, verbose_name='余额')),
                ('in_order_money', models.FloatField(default=0.1, verbose_name='冻结金额')),
                ('is_reviewed', models.IntegerField(choices=[(0, '未提交'), (1, '审核中'), (2, '审核通过'), (-1, '审核未通过')], default=0, verbose_name='是否审核通过')),
                ('desc', models.CharField(blank=True, default='', max_length=4096, null=True, verbose_name='个人签名')),
                ('home_img', models.ImageField(blank=True, null=True, upload_to='', verbose_name='主页图片')),
                ('pay_way', models.IntegerField(choices=[(0, '互免'), (1, '收费')], default=0, verbose_name='收费方式')),
                ('price', models.FloatField(default=0.0, verbose_name='价格')),
                ('price_area', models.CharField(default='0-100', help_text='自动生成，不需要填写', max_length=1024, verbose_name='价格区间')),
                ('visit', models.IntegerField(default=0, verbose_name='访问量')),
            ],
            options={
                'verbose_name': '摄影师',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_card_1', models.ImageField(upload_to='', verbose_name='正面身份证')),
                ('id_card_2', models.ImageField(upload_to='', verbose_name='反面身份证')),
                ('device_1', models.ImageField(upload_to='', verbose_name='使用设备－前面')),
                ('device_2', models.ImageField(upload_to='', verbose_name='使用设备－后面')),
                ('device_3', models.ImageField(upload_to='', verbose_name='使用设备－侧面')),
                ('is_reviewed', models.IntegerField(default=False, verbose_name='是否审核通过')),
                ('comment', models.CharField(default='', max_length=4096, verbose_name='审核意见')),
                ('photographer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wephoto.Photographer')),
            ],
            options={
                'verbose_name': '审核记录',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=48, unique=True, verbose_name='标签名')),
                ('count', models.IntegerField(default=0, verbose_name='使用次数')),
            ],
            options={
                'verbose_name': '标签',
            },
        ),
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='', verbose_name='图片')),
                ('tag', models.CharField(default='', max_length=1024)),
            ],
            options={
                'verbose_name': '上传的图片',
            },
        ),
        migrations.AddField(
            model_name='photographer',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='wephoto.Tag'),
        ),
        migrations.AddField(
            model_name='order',
            name='photographer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wephoto.Photographer', verbose_name='摄影师'),
        ),
    ]
