# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-17 12:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '系统设置',
            },
        ),
        migrations.CreateModel(
            name='Moment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='最后修改日期')),
                ('content', models.CharField(max_length=4096, verbose_name='内容')),
            ],
            options={
                'verbose_name': '发现',
            },
        ),
        migrations.CreateModel(
            name='MomentComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=4096, verbose_name='内容')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='最后修改日期')),
            ],
            options={
                'verbose_name': '发现的评论',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(choices=[(0, '新建'), (1, '进行中'), (2, '已完成'), (3, '已取消')], default=0, verbose_name='订单状态')),
                ('type', models.IntegerField(choices=[(0, '互免'), (1, '收费')], default=0, verbose_name='订单类型')),
                ('price', models.FloatField(default=0.0, verbose_name='价格')),
                ('place', models.CharField(max_length=1024, verbose_name='地点')),
                ('place_type', models.IntegerField(choices=[(0, '室内'), (1, '户外')], default=0, verbose_name='地点类型')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='最后修改日期')),
                ('score', models.IntegerField(blank=True, default=5, verbose_name='分数')),
                ('content', models.CharField(blank=True, default='', max_length=4096, verbose_name='评价内容')),
            ],
            options={
                'verbose_name': '订单',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_card_1', models.ImageField(upload_to='', verbose_name='正面身份证')),
                ('id_card_2', models.ImageField(upload_to='', verbose_name='反面身份证')),
                ('device_1', models.ImageField(upload_to='', verbose_name='使用设备－前面')),
                ('device_2', models.ImageField(upload_to='', verbose_name='使用设备－后面')),
                ('device_3', models.ImageField(upload_to='', verbose_name='使用设备－侧面')),
                ('is_reviewed', models.IntegerField(choices=[(1, '审核中'), (2, '审核通过'), (-1, '审核未通过')], default=1, verbose_name='是否审核通过')),
                ('comment', models.CharField(default='', max_length=4096, verbose_name='审核意见')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='最后修改日期')),
            ],
            options={
                'verbose_name': '审核记录',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=48, unique=True, verbose_name='标签名')),
                ('count', models.IntegerField(default=0, verbose_name='使用次数')),
            ],
            options={
                'verbose_name': '标签',
            },
        ),
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='', verbose_name='图片')),
                ('tag', models.CharField(default='', max_length=1024)),
            ],
            options={
                'verbose_name': '上传的图片',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=32, unique=True, verbose_name='手机')),
                ('username', models.CharField(max_length=1024, verbose_name='用户名')),
                ('password', models.CharField(max_length=1024, verbose_name='密码')),
                ('gender', models.IntegerField(choices=[(0, '男'), (1, '女')], default=0, verbose_name='性别')),
                ('avatar', models.ImageField(blank=True, default='', upload_to='avatar', verbose_name='头像')),
                ('token', models.CharField(blank=True, default='', max_length=4096)),
                ('qq', models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='QQ号')),
                ('wechat', models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='微信号')),
                ('birthday', models.DateField(blank=True, default='1995-01-01', verbose_name='出生年月日')),
                ('money', models.FloatField(blank=True, default=0.0, verbose_name='余额')),
                ('in_order_money', models.FloatField(blank=True, default=0.0, verbose_name='冻结金额')),
                ('bank_card', models.CharField(blank=True, max_length=1024, verbose_name='银行卡')),
                ('address', models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='所在地区')),
                ('order_count', models.IntegerField(blank=True, default=0, verbose_name='已完成订单数')),
                ('user_type', models.BooleanField(choices=[(False, '普通用户'), (True, '摄影师')], default=False, verbose_name='是否为摄影师')),
                ('is_reviewed', models.IntegerField(blank=True, choices=[(0, '未提交'), (1, '审核中'), (2, '审核通过'), (-1, '审核未通过')], default=0, verbose_name='是否审核通过')),
                ('desc', models.CharField(blank=True, default='', max_length=4096, null=True, verbose_name='个人签名')),
                ('home_img', models.ImageField(blank=True, upload_to='', verbose_name='主页图片')),
                ('pay_way', models.IntegerField(blank=True, choices=[(0, '互免'), (1, '收费')], default=0, verbose_name='收费方式')),
                ('price', models.FloatField(blank=True, default=0.0, verbose_name='价格')),
                ('visit', models.IntegerField(blank=True, default=0, verbose_name='访问量')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='最后修改日期')),
                ('album', models.ManyToManyField(blank=True, to='wephoto.UploadedImage', verbose_name='相册')),
                ('likes', models.ManyToManyField(blank=True, related_name='_user_likes_+', to='wephoto.User', verbose_name='收藏')),
                ('tags', models.ManyToManyField(blank=True, null=True, to='wephoto.Tag', verbose_name='用户标签')),
            ],
            options={
                'verbose_name': '用户',
            },
        ),
        migrations.AddField(
            model_name='review',
            name='photographer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wephoto.User'),
        ),
        migrations.AddField(
            model_name='order',
            name='images',
            field=models.ManyToManyField(blank=True, to='wephoto.UploadedImage', verbose_name='评论图片'),
        ),
        migrations.AddField(
            model_name='order',
            name='photographer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_photographer_photographer', to='wephoto.User', verbose_name='摄影师'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_model_user_user', to='wephoto.User', verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='momentcomment',
            name='reply_to',
            field=models.ForeignKey(blank=True, default=None, help_text='如果不是对回复的回复，则为空', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moment_comment_reply_user', to='wephoto.User', verbose_name='回复的用户'),
        ),
        migrations.AddField(
            model_name='momentcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moment_comment_user_user', to='wephoto.User', verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='moment',
            name='comments',
            field=models.ManyToManyField(blank=True, to='wephoto.MomentComment', verbose_name='相关评论'),
        ),
        migrations.AddField(
            model_name='moment',
            name='images',
            field=models.ManyToManyField(blank=True, to='wephoto.UploadedImage'),
        ),
        migrations.AddField(
            model_name='moment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wephoto.User', verbose_name='用户'),
        ),
    ]
