# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-11 14:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wephoto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commonuser',
            name='id',
        ),
        migrations.RemoveField(
            model_name='photographer',
            name='id',
        ),
        migrations.AlterField(
            model_name='commonuser',
            name='avator',
            field=models.ImageField(blank=True, null=True, upload_to='avator', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='commonuser',
            name='username',
            field=models.CharField(max_length=1024, primary_key=True, serialize=False, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='order',
            name='model_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wephoto.CommonUser', verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='order',
            name='photophrapher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wephoto.Photographer', verbose_name='摄影师'),
        ),
        migrations.AlterField(
            model_name='photographer',
            name='avator',
            field=models.ImageField(blank=True, null=True, upload_to='avator', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='photographer',
            name='username',
            field=models.CharField(max_length=1024, primary_key=True, serialize=False, verbose_name='用户名'),
        ),
    ]
