# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-12 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wephoto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonuser',
            name='likes',
            field=models.ManyToManyField(to='wephoto.Photographer'),
        ),
    ]
