# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-11 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wephoto', '0002_auto_20180911_2212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commonuser',
            name='name',
        ),
        migrations.RemoveField(
            model_name='photographer',
            name='name',
        ),
        migrations.AlterField(
            model_name='commonuser',
            name='gender',
            field=models.IntegerField(choices=[(0, '男'), (1, '女')], default=0),
        ),
        migrations.AlterField(
            model_name='commonuser',
            name='phone',
            field=models.CharField(max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='commonuser',
            name='username',
            field=models.CharField(max_length=1024, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='photographer',
            name='gender',
            field=models.IntegerField(choices=[(0, '男'), (1, '女')], default=0),
        ),
        migrations.AlterField(
            model_name='photographer',
            name='phone',
            field=models.CharField(max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='photographer',
            name='username',
            field=models.CharField(max_length=1024, verbose_name='用户名'),
        ),
    ]
